version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.2
  env_file:
    - ../.env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'

    # SMTP Gmail
    AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
    AIRFLOW__SMTP__SMTP_STARTTLS: 'true'
    AIRFLOW__SMTP__SMTP_SSL: 'false'
    AIRFLOW__SMTP__SMTP_PORT: '587'
    AIRFLOW__SMTP__SMTP_USER: ${GMAIL_USER}
    AIRFLOW__SMTP__SMTP_PASSWORD: ${GMAIL_APP_PASSWORD}
    AIRFLOW__SMTP__SMTP_MAIL_FROM: ${GMAIL_USER}

    # Connexion au Data Warehouse (PostgreSQL local → host.docker.internal)
    DB_HOST: host.docker.internal
    DB_PORT: ${DB_PORT:-5432}
    DB_NAME: ${DB_NAME:-datawarehouse}
    DB_USER: ${DB_USER:-postgres}
    DB_PASSWORD: ${DB_PASSWORD}
    RAPPORT_EMAIL: ${RAPPORT_EMAIL:-nyvoaryraherimandimby@gmail.com}

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ../etl:/opt/airflow/etl
    - ../dbt_project:/opt/airflow/dbt_project
    - ../data:/opt/airflow/data
  extra_hosts:
    - "host.docker.internal:host-gateway"
  depends_on:
    postgres-airflow:
      condition: service_healthy

services:

  postgres-airflow:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-airflow-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    command: bash -c "pip install pandas psycopg2-binary requests python-dotenv "dbt-postgres==1.8.2" "dbt-core==1.8.7" && airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email nyvoaryraherimandimby@gmail.com"
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "pip install pandas psycopg2-binary requests python-dotenv "dbt-postgres==1.8.2" "dbt-core==1.8.7" &&
               airflow webserver"
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "pip install pandas psycopg2-binary requests python-dotenv "dbt-postgres==1.8.2" "dbt-core==1.8.7" &&
               airflow scheduler"
    restart: always

volumes:
  postgres-airflow-data:
